
import React, { useState, useMemo } from 'react';
import { SEOAuditReport, CompetitorInsight } from '../types';
import { MetricCard } from './MetricCard';
import { 
  BarChart, 
  Search, 
  Globe, 
  Zap, 
  ShieldCheck, 
  AlertCircle, 
  CheckCircle, 
  TrendingUp, 
  ExternalLink,
  Target,
  ListTodo,
  Columns,
  X,
  Plus,
  Minus,
  ArrowUpDown
} from 'lucide-react';
import { 
  Radar, 
  RadarChart, 
  PolarGrid, 
  PolarAngleAxis, 
  ResponsiveContainer 
} from 'recharts';

interface ReportViewProps {
  report: SEOAuditReport;
}

type SortKey = 'competitor' | 'advantage' | 'threat';
type SortDirection = 'asc' | 'desc';

export const ReportView: React.FC<ReportViewProps> = ({ report }) => {
  const [competitorSearch, setCompetitorSearch] = useState('');
  const [selectedCompetitors, setSelectedCompetitors] = useState<CompetitorInsight[]>([]);
  const [sortKey, setSortKey] = useState<SortKey>('competitor');
  const [sortDirection, setSortDirection] = useState<SortDirection>('asc');

  const radarData = [
    { subject: 'On-Page', A: report.categories.onPage.score },
    { subject: 'Technical', A: report.categories.technical.score },
    { subject: 'Off-Page', A: report.categories.offPage.score },
    { subject: 'Authority', A: report.categories.authority.score },
    { subject: 'Indexing', A: report.categories.indexing.score },
  ];

  const processedCompetitors = useMemo(() => {
    return [...report.competitorInsights]
      .filter(comp => 
        comp.competitor.toLowerCase().includes(competitorSearch.toLowerCase())
      )
      .sort((a, b) => {
        const valA = a[sortKey].toLowerCase();
        const valB = b[sortKey].toLowerCase();
        if (sortDirection === 'asc') {
          return valA.localeCompare(valB);
        } else {
          return valB.localeCompare(valA);
        }
      });
  }, [report.competitorInsights, competitorSearch, sortKey, sortDirection]);

  const toggleCompetitorSelection = (comp: CompetitorInsight) => {
    const isSelected = selectedCompetitors.some(c => c.competitor === comp.competitor);
    if (isSelected) {
      setSelectedCompetitors(selectedCompetitors.filter(c => c.competitor !== comp.competitor));
    } else {
      setSelectedCompetitors([...selectedCompetitors, comp]);
    }
  };

  const handleSort = (key: SortKey) => {
    if (sortKey === key) {
      setSortDirection(sortDirection === 'asc' ? 'desc' : 'asc');
    } else {
      setSortKey(key);
      setSortDirection('asc');
    }
  };

  return (
    <div className="max-w-7xl mx-auto px-4 py-8 space-y-8">
      {/* Header Summary */}
      <div className="bg-white rounded-2xl border border-slate-200 shadow-sm overflow-hidden">
        <div className="bg-indigo-600 px-8 py-10 text-white flex flex-col md:flex-row items-center justify-between gap-8">
          <div>
            <div className="flex items-center gap-2 text-indigo-100 mb-2">
              <Globe size={18} />
              <span className="text-sm font-medium uppercase tracking-widest">Audit for</span>
            </div>
            <h1 className="text-4xl font-black">{report.domain}</h1>
            <p className="text-indigo-100 mt-2 max-w-xl">
              Comprehensive SEO audit generated by Gemini Intelligence. Analyzing technical health, 
              content optimization, and market authority.
            </p>
          </div>
          <div className="flex items-center gap-6">
            <div className="text-center">
              <div className="text-5xl font-black mb-1">{report.overallScore}</div>
              <div className="text-xs font-bold uppercase tracking-tighter text-indigo-200">Overall Score</div>
            </div>
            <div className="h-16 w-px bg-indigo-400 opacity-30" />
            <div className="w-48 h-48 -mr-6 -my-6 hidden lg:block">
               <ResponsiveContainer width="100%" height="100%">
                <RadarChart cx="50%" cy="50%" outerRadius="70%" data={radarData}>
                  <PolarGrid stroke="#ffffff44" />
                  <PolarAngleAxis dataKey="subject" tick={{ fill: '#ffffffcc', fontSize: 10 }} />
                  <Radar
                    name="SEO"
                    dataKey="A"
                    stroke="#fff"
                    fill="#fff"
                    fillOpacity={0.3}
                  />
                </RadarChart>
               </ResponsiveContainer>
            </div>
          </div>
        </div>
      </div>

      {/* Metric Cards Grid */}
      <div className="grid grid-cols-1 md:grid-cols-3 lg:grid-cols-5 gap-4">
        <MetricCard 
          label="On-Page" 
          metric={report.categories.onPage} 
          icon={<Search size={20} />} 
        />
        <MetricCard 
          label="Technical" 
          metric={report.categories.technical} 
          icon={<Zap size={20} />} 
        />
        <MetricCard 
          label="Off-Page" 
          metric={report.categories.offPage} 
          icon={<TrendingUp size={20} />} 
        />
        <MetricCard 
          label="Authority" 
          metric={report.categories.authority} 
          icon={<ShieldCheck size={20} />} 
        />
        <MetricCard 
          label="Indexing" 
          metric={report.categories.indexing} 
          icon={<Globe size={20} />} 
        />
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        {/* Left Column: Action Plan & Findings */}
        <div className="lg:col-span-2 space-y-6">
          <section className="bg-white rounded-xl border border-slate-200 p-6">
            <div className="flex items-center gap-2 mb-6">
              <div className="p-2 bg-blue-50 text-blue-600 rounded-lg">
                <ListTodo size={20} />
              </div>
              <h2 className="text-xl font-bold text-slate-900">Recommended Action Plan</h2>
            </div>
            <div className="space-y-4">
              {report.actionPlan.map((step, idx) => (
                <div key={idx} className="flex gap-4 p-4 rounded-lg border border-slate-100 hover:border-indigo-100 hover:bg-slate-50 transition-colors">
                  <div className={`mt-1 px-2 py-1 rounded text-[10px] font-bold uppercase tracking-wide flex-shrink-0 self-start ${
                    step.priority === 'High' ? 'bg-red-100 text-red-600' : 
                    step.priority === 'Medium' ? 'bg-yellow-100 text-yellow-600' : 'bg-blue-100 text-blue-600'
                  }`}>
                    {step.priority}
                  </div>
                  <div>
                    <h4 className="font-bold text-slate-800 mb-1">{step.task}</h4>
                    <p className="text-sm text-slate-600 leading-relaxed">{step.impact}</p>
                  </div>
                </div>
              ))}
            </div>
          </section>

          {/* Key Findings */}
          <section className="bg-white rounded-xl border border-slate-200 p-6">
            <div className="flex items-center gap-2 mb-6">
              <div className="p-2 bg-emerald-50 text-emerald-600 rounded-lg">
                <BarChart size={20} />
              </div>
              <h2 className="text-xl font-bold text-slate-900">Intelligence Insights</h2>
            </div>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              {report.keyFindings.map((finding, idx) => (
                <div key={idx} className="p-4 rounded-xl bg-slate-50 border border-slate-100">
                  <div className="flex items-center justify-between mb-2">
                    <span className="text-[10px] font-bold text-indigo-500 uppercase tracking-widest">{finding.category}</span>
                    {finding.type === 'Positive' ? <CheckCircle size={14} className="text-emerald-500" /> : <AlertCircle size={14} className="text-red-400" />}
                  </div>
                  <p className="text-sm text-slate-700 font-medium">{finding.message}</p>
                </div>
              ))}
            </div>
          </section>

          {/* Section: Side-by-Side Comparison Matrix */}
          {selectedCompetitors.length > 0 && (
            <section className="bg-slate-900 rounded-2xl p-6 text-white shadow-2xl animate-in slide-in-from-bottom-4 duration-500">
              <div className="flex items-center justify-between mb-8">
                <div className="flex items-center gap-2">
                  <div className="p-2 bg-indigo-500/20 text-indigo-400 rounded-lg">
                    <Columns size={20} />
                  </div>
                  <h2 className="text-xl font-bold">Side-by-Side Comparison</h2>
                </div>
                <button 
                  onClick={() => setSelectedCompetitors([])}
                  className="text-slate-400 hover:text-white flex items-center gap-1 text-sm font-medium"
                >
                  <X size={16} /> Clear All
                </button>
              </div>

              <div className="overflow-x-auto pb-4 custom-scrollbar">
                <table className="w-full text-left border-collapse min-w-[600px]">
                  <thead>
                    <tr>
                      <th className="pb-4 pt-2 border-b border-slate-800 text-slate-400 font-bold uppercase tracking-wider text-xs w-1/4">Metric</th>
                      {selectedCompetitors.map((comp, idx) => (
                        <th key={idx} className="pb-4 pt-2 px-4 border-b border-slate-800 text-indigo-400 font-black uppercase text-sm truncate">
                          {comp.competitor}
                        </th>
                      ))}
                    </tr>
                  </thead>
                  <tbody>
                    <tr>
                      <td className="py-6 border-b border-slate-800 font-bold text-slate-300">Market Advantage</td>
                      {selectedCompetitors.map((comp, idx) => (
                        <td key={idx} className="py-6 px-4 border-b border-slate-800">
                          <div className="bg-emerald-500/10 border border-emerald-500/20 p-3 rounded-lg text-emerald-400 text-xs leading-relaxed">
                            {comp.advantage}
                          </div>
                        </td>
                      ))}
                    </tr>
                    <tr>
                      <td className="py-6 border-b border-slate-800 font-bold text-slate-300">Strategic Threat</td>
                      {selectedCompetitors.map((comp, idx) => (
                        <td key={idx} className="py-6 px-4 border-b border-slate-800">
                          <div className="bg-rose-500/10 border border-rose-500/20 p-3 rounded-lg text-rose-400 text-xs leading-relaxed">
                            {comp.threat}
                          </div>
                        </td>
                      ))}
                    </tr>
                  </tbody>
                </table>
              </div>
            </section>
          )}
        </div>

        {/* Right Column: Competitor List & Sources */}
        <div className="space-y-8">
          <section className="bg-white rounded-xl border border-slate-200 p-6 flex flex-col h-full shadow-sm">
            <div className="flex items-center justify-between mb-6">
              <div className="flex items-center gap-2">
                <div className="p-2 bg-purple-50 text-purple-600 rounded-lg">
                  <Target size={20} />
                </div>
                <h2 className="text-xl font-bold text-slate-900">Market Intelligence</h2>
              </div>
            </div>

            {/* Search Bar for Competitors */}
            <div className="relative mb-4">
              <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
                <Search size={14} className="text-slate-400" />
              </div>
              <input
                type="text"
                placeholder="Filter competitors..."
                value={competitorSearch}
                onChange={(e) => setCompetitorSearch(e.target.value)}
                className="block w-full pl-9 pr-3 py-2 bg-slate-50 border border-slate-200 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:border-transparent transition-all"
              />
            </div>

            {/* Sort Controls */}
            <div className="flex items-center gap-1 mb-6 overflow-x-auto pb-1 custom-scrollbar">
              <span className="text-[10px] font-black uppercase text-slate-400 mr-2 flex-shrink-0">Sort By:</span>
              {(['competitor', 'advantage', 'threat'] as SortKey[]).map((key) => (
                <button
                  key={key}
                  onClick={() => handleSort(key)}
                  className={`flex items-center gap-1.5 px-3 py-1.5 rounded-full text-xs font-bold transition-all border whitespace-nowrap ${
                    sortKey === key 
                      ? 'bg-indigo-600 text-white border-indigo-600' 
                      : 'bg-white text-slate-600 border-slate-200 hover:bg-slate-50'
                  }`}
                >
                  {key === 'competitor' ? 'Name' : key.charAt(0).toUpperCase() + key.slice(1)}
                  {sortKey === key && (
                    <ArrowUpDown size={12} className={`transition-transform duration-200 ${sortDirection === 'desc' ? 'rotate-180' : ''}`} />
                  )}
                </button>
              ))}
            </div>

            <div className="space-y-3 overflow-y-auto max-h-[600px] pr-2 custom-scrollbar">
              {processedCompetitors.length > 0 ? (
                processedCompetitors.map((comp, idx) => {
                  const isSelected = selectedCompetitors.some(c => c.competitor === comp.competitor);
                  return (
                    <div 
                      key={idx} 
                      onClick={() => toggleCompetitorSelection(comp)}
                      className={`group cursor-pointer p-4 rounded-xl border transition-all duration-200 ${
                        isSelected 
                          ? 'bg-indigo-50 border-indigo-200 shadow-sm ring-1 ring-indigo-200' 
                          : 'bg-white border-slate-100 hover:border-slate-300 hover:shadow-sm'
                      }`}
                    >
                      <div className="flex items-center justify-between mb-3">
                        <div className="flex items-center gap-2">
                          <div className={`w-2 h-2 rounded-full ${isSelected ? 'bg-indigo-600' : 'bg-slate-300 group-hover:bg-purple-400'}`} />
                          <span className={`font-black text-sm uppercase tracking-tight ${isSelected ? 'text-indigo-900' : 'text-slate-800'}`}>
                            {comp.competitor}
                          </span>
                        </div>
                        <div className={`p-1 rounded-md transition-colors ${isSelected ? 'bg-indigo-600 text-white' : 'bg-slate-50 text-slate-400'}`}>
                          {isSelected ? <Minus size={14} /> : <Plus size={14} />}
                        </div>
                      </div>
                      <p className="text-[11px] text-slate-500 line-clamp-2 leading-relaxed italic">
                        "{comp.advantage.slice(0, 100)}..."
                      </p>
                    </div>
                  );
                })
              ) : (
                <div className="text-center py-8">
                  <p className="text-sm text-slate-500 italic">No competitors found</p>
                </div>
              )}
            </div>
            
            {selectedCompetitors.length > 0 && (
              <div className="mt-6 pt-4 border-t border-slate-100">
                <div className="flex items-center justify-between text-xs font-bold text-slate-400 uppercase tracking-widest">
                  <span>Comparing</span>
                  <span className="bg-indigo-600 text-white px-2 py-0.5 rounded-full">{selectedCompetitors.length}</span>
                </div>
              </div>
            )}
          </section>

          {report.groundingSources && report.groundingSources.length > 0 && (
            <section className="bg-slate-900 rounded-xl p-6 text-white shadow-sm">
               <h3 className="text-xs font-bold uppercase tracking-widest text-slate-400 mb-4 flex items-center gap-2">
                <ExternalLink size={12} />
                Verification Sources
              </h3>
              <div className="space-y-3">
                {report.groundingSources.slice(0, 5).map((source, idx) => (
                  <a 
                    key={idx} 
                    href={source.uri} 
                    target="_blank" 
                    rel="noopener noreferrer"
                    className="block text-sm text-slate-300 hover:text-white transition-colors truncate"
                  >
                    {source.title || source.uri}
                  </a>
                ))}
              </div>
            </section>
          )}
        </div>
      </div>
      <style>{`
        .custom-scrollbar::-webkit-scrollbar {
          width: 4px;
          height: 4px;
        }
        .custom-scrollbar::-webkit-scrollbar-track {
          background: transparent;
        }
        .custom-scrollbar::-webkit-scrollbar-thumb {
          background: #cbd5e1;
          border-radius: 10px;
        }
        .custom-scrollbar:hover::-webkit-scrollbar-thumb {
          background: #94a3b8;
        }
        @keyframes slideInUp {
          from { opacity: 0; transform: translateY(20px); }
          to { opacity: 1; transform: translateY(0); }
        }
        .animate-in {
          animation: slideInUp 0.4s ease-out forwards;
        }
      `}</style>
    </div>
  );
};
