
import React from 'react';
import { SEOAuditReport } from '../types';
import { MetricCard } from './MetricCard';
import { 
  BarChart, 
  Search, 
  Globe, 
  Zap, 
  ShieldCheck, 
  AlertCircle, 
  CheckCircle, 
  TrendingUp, 
  ExternalLink,
  Target,
  ListTodo
} from 'lucide-react';
import { 
  Radar, 
  RadarChart, 
  PolarGrid, 
  PolarAngleAxis, 
  ResponsiveContainer 
} from 'recharts';

interface ReportViewProps {
  report: SEOAuditReport;
}

export const ReportView: React.FC<ReportViewProps> = ({ report }) => {
  const radarData = [
    { subject: 'On-Page', A: report.categories.onPage.score },
    { subject: 'Technical', A: report.categories.technical.score },
    { subject: 'Off-Page', A: report.categories.offPage.score },
    { subject: 'Authority', A: report.categories.authority.score },
    { subject: 'Indexing', A: report.categories.indexing.score },
  ];

  return (
    <div className="max-w-7xl mx-auto px-4 py-8 space-y-8">
      {/* Header Summary */}
      <div className="bg-white rounded-2xl border border-slate-200 shadow-sm overflow-hidden">
        <div className="bg-indigo-600 px-8 py-10 text-white flex flex-col md:flex-row items-center justify-between gap-8">
          <div>
            <div className="flex items-center gap-2 text-indigo-100 mb-2">
              <Globe size={18} />
              <span className="text-sm font-medium uppercase tracking-widest">Audit for</span>
            </div>
            <h1 className="text-4xl font-black">{report.domain}</h1>
            <p className="text-indigo-100 mt-2 max-w-xl">
              Comprehensive SEO audit generated by Gemini Intelligence. Analyzing technical health, 
              content optimization, and market authority.
            </p>
          </div>
          <div className="flex items-center gap-6">
            <div className="text-center">
              <div className="text-5xl font-black mb-1">{report.overallScore}</div>
              <div className="text-xs font-bold uppercase tracking-tighter text-indigo-200">Overall Score</div>
            </div>
            <div className="h-16 w-px bg-indigo-400 opacity-30" />
            <div className="w-48 h-48 -mr-6 -my-6 hidden lg:block">
               <ResponsiveContainer width="100%" height="100%">
                <RadarChart cx="50%" cy="50%" outerRadius="70%" data={radarData}>
                  <PolarGrid stroke="#ffffff44" />
                  <PolarAngleAxis dataKey="subject" tick={{ fill: '#ffffffcc', fontSize: 10 }} />
                  <Radar
                    name="SEO"
                    dataKey="A"
                    stroke="#fff"
                    fill="#fff"
                    fillOpacity={0.3}
                  />
                </RadarChart>
              </ResponsiveContainer>
            </div>
          </div>
        </div>
      </div>

      {/* Metric Cards Grid */}
      <div className="grid grid-cols-1 md:grid-cols-3 lg:grid-cols-5 gap-4">
        <MetricCard 
          label="On-Page" 
          metric={report.categories.onPage} 
          icon={<Search size={20} />} 
        />
        <MetricCard 
          label="Technical" 
          metric={report.categories.technical} 
          icon={<Zap size={20} />} 
        />
        <MetricCard 
          label="Off-Page" 
          metric={report.categories.offPage} 
          icon={<TrendingUp size={20} />} 
        />
        <MetricCard 
          label="Authority" 
          metric={report.categories.authority} 
          icon={<ShieldCheck size={20} />} 
        />
        <MetricCard 
          label="Indexing" 
          metric={report.categories.indexing} 
          icon={<Globe size={20} />} 
        />
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        {/* Action Plan */}
        <div className="lg:col-span-2 space-y-6">
          <section className="bg-white rounded-xl border border-slate-200 p-6">
            <div className="flex items-center gap-2 mb-6">
              <div className="p-2 bg-blue-50 text-blue-600 rounded-lg">
                <ListTodo size={20} />
              </div>
              <h2 className="text-xl font-bold text-slate-900">Recommended Action Plan</h2>
            </div>
            <div className="space-y-4">
              {report.actionPlan.map((step, idx) => (
                <div key={idx} className="flex gap-4 p-4 rounded-lg border border-slate-100 hover:border-indigo-100 hover:bg-slate-50 transition-colors">
                  <div className={`mt-1 px-2 py-1 rounded text-[10px] font-bold uppercase tracking-wide flex-shrink-0 self-start ${
                    step.priority === 'High' ? 'bg-red-100 text-red-600' : 
                    step.priority === 'Medium' ? 'bg-yellow-100 text-yellow-600' : 'bg-blue-100 text-blue-600'
                  }`}>
                    {step.priority}
                  </div>
                  <div>
                    <h4 className="font-bold text-slate-800 mb-1">{step.task}</h4>
                    <p className="text-sm text-slate-600 leading-relaxed">{step.impact}</p>
                  </div>
                </div>
              ))}
            </div>
          </section>

          {/* Key Findings */}
          <section className="bg-white rounded-xl border border-slate-200 p-6">
            <div className="flex items-center gap-2 mb-6">
              <div className="p-2 bg-emerald-50 text-emerald-600 rounded-lg">
                <BarChart size={20} />
              </div>
              <h2 className="text-xl font-bold text-slate-900">Intelligence Insights</h2>
            </div>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              {report.keyFindings.map((finding, idx) => (
                <div key={idx} className="p-4 rounded-xl bg-slate-50 border border-slate-100">
                  <div className="flex items-center justify-between mb-2">
                    <span className="text-[10px] font-bold text-indigo-500 uppercase tracking-widest">{finding.category}</span>
                    {finding.type === 'Positive' ? <CheckCircle size={14} className="text-emerald-500" /> : <AlertCircle size={14} className="text-red-400" />}
                  </div>
                  <p className="text-sm text-slate-700 font-medium">{finding.message}</p>
                </div>
              ))}
            </div>
          </section>
        </div>

        {/* Competitor Insights & Sources */}
        <div className="space-y-8">
          <section className="bg-white rounded-xl border border-slate-200 p-6">
            <div className="flex items-center gap-2 mb-6">
              <div className="p-2 bg-purple-50 text-purple-600 rounded-lg">
                <Target size={20} />
              </div>
              <h2 className="text-xl font-bold text-slate-900">Market Intelligence</h2>
            </div>
            <div className="space-y-6">
              {report.competitorInsights.map((comp, idx) => (
                <div key={idx} className="space-y-3">
                  <div className="flex items-center gap-2">
                    <div className="w-1.5 h-1.5 rounded-full bg-purple-500" />
                    <span className="font-black text-slate-800">{comp.competitor}</span>
                  </div>
                  <div className="pl-3.5 space-y-2">
                    <div className="text-xs">
                      <span className="font-bold text-emerald-600 uppercase">Edge: </span>
                      <span className="text-slate-600">{comp.advantage}</span>
                    </div>
                    <div className="text-xs">
                      <span className="font-bold text-rose-500 uppercase">Threat: </span>
                      <span className="text-slate-600">{comp.threat}</span>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </section>

          {report.groundingSources && report.groundingSources.length > 0 && (
            <section className="bg-slate-900 rounded-xl p-6 text-white">
               <h3 className="text-xs font-bold uppercase tracking-widest text-slate-400 mb-4 flex items-center gap-2">
                <ExternalLink size={12} />
                Verification Sources
              </h3>
              <div className="space-y-3">
                {report.groundingSources.slice(0, 5).map((source, idx) => (
                  <a 
                    key={idx} 
                    href={source.uri} 
                    target="_blank" 
                    rel="noopener noreferrer"
                    className="block text-sm text-slate-300 hover:text-white transition-colors truncate"
                  >
                    {source.title || source.uri}
                  </a>
                ))}
              </div>
            </section>
          )}
        </div>
      </div>
    </div>
  );
};
